### ISSUE TITLE
2Capcha solve issue

### ISSUE THREAD

**Issue by EvoNeck** [Tips-Discord/Cwelium#16]
(failed to do request: Get "http://2captcha.com/res.php?key={myKey}&action=get&id=76398750934": http2: unsupported scheme)
My API key cannot fail to work, there is a balance

**Comment by Tips-Discord** [comment]
brhh xd

**Comment by EvoNeck** [comment]
help pls
:(

**Comment by Tips-Discord** [comment]
1 how did you broke the url lol

**Comment by EvoNeck** [comment]
i didnt
wdym

**Comment by EvoNeck** [comment]
uhhh

**Comment by EvoNeck** [comment]
:|

**Comment by EvoNeck** [comment]
Alr
fix when

**Comment by Tips-Discord** [comment]
i will try to fix it

**Comment by EvoNeck** [comment]
i hope so
